import { Inter } from "next/font/google";
import "./globals.css";
import Nav from './component/Nav.jsx'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hello",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        {children}
        </body>
    </html>
  );
}
